title: Mismatched tags or brackets
hero_image: images/banner.png
description: Mismatched tags or brackets.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Mismatched tags or brackets
